### PR TITLE
Add unpublished idl documents to iterate on

### PR DESCRIPTION
**Pull request by sloretz**
~~~This PR combines the 4 IDL design documents into one page.~~~

Edit: PR now is the bare minimum to start parallelizing design doc work

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Is this PR the first of a series?

As this page is getting pretty long and doesn't have the information for C generated structures I think we could benefit from more combination in that document.
For example I did found summary tables for types useful in the past: https://github.com/ros2/ros2/wiki/About-ROS-Interfaces#211-field-types (rather than 1 table per language)

**Comment by sloretz** [comment]
@mikaelarguedas Now it's the first of a series. The content of this PR has been replaced to add two unpublished documents. One is a copy of the existing interface definition, the other is a stub for new content

**Review by dirk-thomas — DISMISSED** [review]

**Comment by dirk-thomas** [comment]
> One is a copy of the existing interface definition, the other is a stub for new content

In order to maintain the history please use one commit duplicating the existing file without any changes and a separate commit to update the header. The second commit can also contain the new document (I don't mind about that one). This should be merged without squashing then.

**Comment by sloretz** [comment]
> In order to maintain the history please use one commit duplicating the existing file without any changes 

Done 97c52bb  and ~~~aef9f12~~~ 031af7a

**Review by dirk-thomas — APPROVED** [review]
Thanks for iterating on this.

**Pull request merged**
