### PR TITLE
Embedded ros2

### PR DESCRIPTION
**Pull request by clalancette**
Originally opened by @iluetkeb, in PR https://github.com/ros2/design/pull/197, moving to a branch on the repo directly.

### CODE REVIEW

**Comment by iluetkeb** [comment]
@clalancette Uh, thanks for moving this, but neither I nor any of the other micro-ROS people can push to this branch... This means we can't address comments!

My motivation was to be able to include more people than just us, but of course I did expect that we would still be able to access it ;-)

Please add at least @BorjaOuterelo @ralph-lange @vmayoral and myself. Thank you.

**Comment by clalancette** [comment]
> @clalancette Uh, thanks for moving this, but neither I nor any of the other micro-ROS people can push to this branch... This means we can't address comments!
> 
> My motivation was to be able to include more people than just us, but of course I did expect that we would still be able to access it ;-)
> 
> Please add at least @BorjaOuterelo @ralph-lange @vmayoral and myself. Thank you.

Sorry, I misunderstood here.  I don't think that what you are proposing is possible in GitHub; as far as I can tell, you can only allow/disallow people access to the repository, not to the individual branches.  What I'm going to do instead is to fork this repository into my own individual account, add you all as collaborators to that repository, and then open a PR from that fork.  I think that should let the 4 of you push (we can add others if they want).

**Comment by iluetkeb** [comment]
@clalancette In general, please allow us some time to respond before making changes, please.

If you don't want to add us to the design repository, we might as well use the microROS organization for this. It fits thematically and we could certainly add collaborators there. I would have to discuss with the others before making non-OFERA people admin, but personally I would be open to that, and I think for the code parts of the project, this would be required anyway.

However, I would prefer if the ROS 2-org repositories would become more open to non-OSRF people. In the last couple of years, github has added a number of features to manage shared repositories in a fairly flexible manner, so this could be done in a controlled way.

One ingredient would be branch rules (found in Settings/Branches), which can restrict what's possible for certain branches, including with wildcard for branches (so you can have defaults).
See https://help.github.com/articles/configuring-protected-branches/

Moreover, you can have "code owners" for certain parts of the repository, which would allow you to make a certain group of people (such as OSRF employees) mandatory reviewers for any pull request. See https://blog.github.com/2017-07-06-introducing-code-owners/ for more information.

**Comment by dirk-thomas** [comment]
The ROS 2 design repository is the "central" location to contain ROS 2 specific documentation. So I recommend to host the proposed article here (rather than somewhere else).

The ROS 2 repositories are open - that doesn't necessarily imply "write access for everyone". The workflow on GitHub using pull requests allows everyone to contribute. People can comment and even make edit suggestions to any existing repository / branch / PR - if desired even through the web UI.

If you prefer to give people direct write access that should be possible by granting them permissions to the branch a PR is being created from - e.g. for #197 to https://github.com/microROS/design/tree/embedded_ROS2.

Anytime a PR is ready to be merged we are happy to do so - the article doesn't have to be "final" - even in draft state it can be merged and iterated on afterwards in separate PRs.

---

Therefore I would recommend to proceed as follows:
* closing #199
* reopening #197
* continue the discussion there, let users contribute either using PRs against the branch of the PR (or through the web UI directly)
* whenever a state is reached request the PR to be merged and someone with write access to the design repo will trigger the merge
* (iterate with additional PRs on the article if necessary)

I guess "reopening #197" needs to be done by someone with write access. If you think the suggested steps make I am happy to do it.

**Comment by iluetkeb** [comment]
@dirk-thomas Makes sense to me, thanks.

**Comment by BorjaOuterelo** [comment]
@dirk-thomas I am also happy with your proposal.

**Comment by dirk-thomas** [comment]
Done.

**Pull request closed without merging**
