### PR TITLE
Mark the rpc article as published.

### PR DESCRIPTION
**Pull request by tfoote**

### CODE REVIEW

**Comment by tfoote** [comment]
Please review for publishing. I need to add the image. I'll do so shortly.

**Comment by tfoote** [comment]
Image added

**Comment by tfoote** [comment]
merged @wjwwood 's feedback in #18 . and rebased.

**Comment by wjwwood** [comment]
+1

**Comment by gerkey** [comment]
I made a bunch of language tweaks in 1c2bab09ccc39804fdff20b6f19d35643ab8b44c.  That probably should have been a pull request to this branch, but, oh, well.

+1

**Comment by wjwwood** [comment]
Still +1 from me, it's probably ok to merge?

**Pull request merged**
