### PR TITLE
lock bundler version

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fix failing CI on the default branch.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Ruby 2.1 has ended support. I think an optimal fix would be to try updating the ruby version to something more current.

**Comment by dirk-thomas** [comment]
> I think an optimal fix would be to try updating the ruby version to something more current.

Please feel free to do so in a follow up PR. This patch makes the CI pass with the same versions as before in order to continue merging other PRs.

**Review by wjwwood — APPROVED** [review]
It would be better to update to the latest version (or revisit GitHub's recommendations about this), but I guess this gets it going again.

**Comment by dirk-thomas** [comment]
See follow up work in #211.

**Pull request merged**
