### PR TITLE
require Python 3.5

### PR DESCRIPTION
**Pull request by dirk-thomas**
Only merge after the switch to Xenial.

### CODE REVIEW

**Comment by jack-oquin** [comment]
What is the rationale for this change?

**Comment by wjwwood** [comment]
We're moving our target platform to be Xenial and it has Python 3.5. There are features in 3.5 that we want to use, so we're making it the minimum.

**Comment by dirk-thomas** [comment]
This still needs review.

**Comment by wjwwood** [comment]
+1

**Pull request merged**
