### PR TITLE
avoid the term legacy for .msg/.srv/.action file format

### PR DESCRIPTION
**Pull request by dirk-thomas**
While we use IDL in the internal pipeline and in all message generators `.msg`/.`srv`/.`action` files are unlikely to be deprecated but will continue to be used if the additional IDL features are not needed.

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]
LGTM

**Comment by mxgrey** [comment]
Just a thought: What about calling them "simplified interface definitions"? Or maybe some other descriptive term to differentiate from IDL?

**Comment by jacobperron** [comment]
I've always differentiated them as "ROS interfaces" verses IDL interfaces.

**Comment by mxgrey** [comment]
I'm a little worried that terminology might give the appearance that IDL isn't supported by ROS2, but I don't know how legitimate my concern is.

**Pull request merged**
