### PR TITLE
history_depth is actually just depth

### PR DESCRIPTION
**Pull request by mikeferguson**
There isn't much documentation on QoS overrides - and many resources that I came across still link back to this (somewhat outdated) design document. Hopefully updating the parameter name here will save some people time in the future.

### CODE REVIEW

**Comment by mikeferguson** [comment]
For easy reference - this is the commit that implemented the design: https://github.com/ros2/rclcpp/commit/71a58d40f19160b1d1ba8f1f408702acaea94fde and the qos_overriding_options.hpp has not been altered since

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by MichaelOrlov** [comment]
@mjcarroll @sloretz Friendly ping to merge this PR.

**Review by sloretz — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
