### PR TITLE
legacy char now maps to int in python

### PR DESCRIPTION
**Pull request by mikaelarguedas**
redo of https://github.com/ros2/design/pull/221 but targeting the legacy design doc for `msg`.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This article starts with:

> With the transition to use ``IDL`` for specifying interfaces in ROS 2 Dashing this article has been superseded by ...

So I am not sure it makes sense to update it.

**Comment by mikaelarguedas** [comment]
I understand your point.
What prompted this initially is that crystal code setting fields of type `char` in messages is now failing to run on master, and I was not able to find resources explaining that it was now mapping to an `int`.

Is there a place discussing the support (or discontinued support) of `msg` in Dashing and what the generated datastructures will be like for people using `msg` files?

**Comment by dirk-thomas** [comment]
Please see https://github.com/ros2/design/pull/221#discussion_r269296677. The change basically restores compatibility to how it is being mapped in ROS 1.

**Comment by mikaelarguedas** [comment]
Thanks for the answer, I replied in #221 . Closing this invalid PR then

**Pull request closed without merging**
