### PR TITLE
Clarify ROS default values will be used in default constructor

### PR DESCRIPTION
**Pull request by dhood**
@mikaelarguedas explained this to me in https://github.com/ros-simulation/gazebo_ros_pkgs/pull/793#discussion_r209356781

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
I think there is still misunderstanding here.

In this article, "default value" always refers to the default value provided in the msg file.

We don't have the concept of "No default value at all" as we define default values for all the types we define in the ROS IDL format (detailed in [this article](http://design.ros2.org/articles/interface_definition.html))

**Comment by dhood** [comment]
since `char` wasn't listed in the article with common defaults I thought it was an example of the 'no default' category. I tried to clarify there's always a default in 93a6c39

**Comment by mikaelarguedas** [comment]
As this paragraph was duplicated below, is it possible to update the following lines as well ?

**Comment by dhood** [comment]
Other sentence updated in 77de52d8fb73f78d89bdb61d3263021d8e4d5309

**Comment by mikaelarguedas** [comment]
lgtm.
Maybe @clalancette wants to review as he has the most context on this

**Comment by clalancette** [comment]
This clarification looks fine to me!  I just corrected some spelling, otherwise, I think this is good to go.

**Comment by dhood** [comment]
thanks to you both!

**Pull request merged**
