### PR TITLE
moving analytics into the head block

### PR DESCRIPTION
**Pull request by tfoote**
This is as per google search console email.

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]

**Comment by dirk-thomas** [comment]
This is commonly done at the end of the body to avoid slowing down the page loading.

**Comment by wjwwood** [comment]
That's why I had it there to begin with, but @tfoote said he needed it to move it based on a recommendation from some Google search panel or something like that.

**Comment by tfoote** [comment]
From the search console verification steps: 
```
Recommended: Google Analytics
Use your Google Analytics account.
You must be using the asynchronous tracking code .
Your tracking code should be in the <head> section of your page.
You must have the "edit" permission for the Analytics web property.
The Google Analytics tracking code is used only to verify site ownership. No Google Analytics data will be accessed.
```

I believe that the new asynchronous tracking snippets also allow much of the work to be done in parallel with the main render path. 

However we could probably revert this since it also appears to work find at the end of the body.

**Comment by wjwwood** [comment]
I don't care either way. Probably won't impact performance too much even in the header.

**Pull request merged**
